### ISSUE TITLE
Breite der zentrierten Textblöcke

### ISSUE THREAD

**Issue by stephaniecuerel** [Sophia27/appuri#1]
Kann man die zentrierten Textblöcke auf ca. 70-80% der Breite laufen lassen?

<img width="1779" alt="Bildschirmfoto 2023-06-27 um 14 01 14" src="https://github.com/Sophia27/appuri/assets/112517194/3dc7d174-e8f1-42e0-a654-7ba729677a3f">

**Comment by Sophia27** [comment]
done
