### ISSUE TITLE
Video am Ende wieder auf Anfangstatus zurücksetzen

### ISSUE THREAD

**Issue by stephaniecuerel** [Sophia27/appuri#2]
Wenn das Video fertig ist, bleibt es jetzt einfach stehen. Könnte es wieder ausblenden und der Playbutton erscheinen? Sodass man eigentlich wieder am Anfang ist.

<img width="1792" alt="Bildschirmfoto 2023-06-27 um 15 06 04" src="https://github.com/Sophia27/appuri/assets/112517194/be8139d8-7441-421e-ac01-f00c76fc98e4">

**Comment by Sophia27** [comment]
oke!
