### ISSUE TITLE
Seitenleisten für Mobile und Desktop neu einfügen

### ISSUE THREAD

**Issue by stephaniecuerel** [Sophia27/appuri#3]
Sind abgelegt unter Webseite > Material > 04_Seitenleiste

**Comment by Sophia27** [comment]
@stephaniecuerel  die Seitenleisten müssten gepfadet werden 🐙

**Comment by stephaniecuerel** [comment]
@Sophia27 Sind neu abgelegt

**Comment by Sophia27** [comment]
Habs a mol eingefüagt. Was meinst @stephaniecuerel ?
