### ISSUE TITLE
Mini Titel anpassen

### ISSUE THREAD

**Issue by stephaniecuerel** [Sophia27/appuri#4]
Diese Minititel mehr der App anpassen (Kleiner, Futter Medium, Laufweite)
Hier sind die Specs: https://xd.adobe.com/view/96373ebc-19cc-4452-a48d-cad82cc9d5ed-c364/

<img width="1933" alt="Bildschirmfoto 2023-06-27 um 15 51 57" src="https://github.com/Sophia27/appuri/assets/112517194/56b288ad-6d40-4e5e-9b00-f7e453e6ed47">

**Comment by Sophia27** [comment]
Bitte checken @stephaniecuerel

**Comment by stephaniecuerel** [comment]
Habe hier noch Mobile ergänzt:
https://xd.adobe.com/view/eec047d8-a492-4e7e-84a3-ebbf6d88a7b0-bb93/

Bei Mobile fände ich es schön, wenn die Type etwas mehr Luft hätte zum Rand.

**Comment by Sophia27** [comment]
so?
