### ISSUE TITLE
Download Overlay 

### ISSUE THREAD

**Issue by stephaniecuerel** [Sophia27/appuri#7]
Beim Overlay fände ich es cool, wenn es abgedunkelt und geblurrt werden könnte wie im urprünglichen design. 
Und anstatt dem Close Button würde ich ein x machen, damit nicht zwei Buttons übereinanderliegen

<img width="1792" alt="Bildschirmfoto 2023-06-27 um 16 38 19" src="https://github.com/Sophia27/appuri/assets/112517194/13efa6e5-19b2-4e54-a12a-3b303515ebd3">
<img width="2032" alt="Bildschirmfoto 2023-06-27 um 16 39 15" src="https://github.com/Sophia27/appuri/assets/112517194/8be07fe3-77bd-4e18-ba3c-b411ccb565d7">

**Comment by Sophia27** [comment]
oke!

**Comment by stephaniecuerel** [comment]
Sehe nur dunkler aber nicht geblurrt. kann das sein?

**Comment by Sophia27** [comment]
![Uploading Bildschirmfoto 2023-06-28 um 08.37.20.png…]()
Bei mir sieht es so aus.
